{
 "title": "New dashboard Copy",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Task Manager microservices kube deployment status ready",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=~\"login-service|note-service|user-service|team-service|task-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node RAM %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Manager microservices membership healthy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "envoy_cluster_membership_healthy{envoy_cluster_name=~\"login_cluster|note_cluster|task_cluster|team_cluster|user_cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "cluster:node_cpu:ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Envoy allowed jwt requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "envoy_http_jwt_authn_allowed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Envoy jwt denied requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "envoy_http_jwt_authn_denied", "legendFormat": "__auto" }
   ]
  }
 ]
}